/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */
import type { SafeUserProfileDto } from './safeUserProfileDto';

export interface AuthMeResponseDto {
  user: SafeUserProfileDto;
}
