/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

/**
 * Categoria da tarefa
 */
export type CreateTaskDtoCategory = typeof CreateTaskDtoCategory[keyof typeof CreateTaskDtoCategory];


export const CreateTaskDtoCategory = {
  TRABALHO: 'TRABALHO',
  ESTUDOS: 'ESTUDOS',
  PESSOAL: 'PESSOAL',
  OUTROS: 'OUTROS',
} as const;
