/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */
import type { CreateUserDtoRole } from './createUserDtoRole';

export interface CreateUserDto {
  /**
     * @minLength 2
     * @maxLength 120
     */
  name: string;
  /** @maxLength 254 */
  email: string;
  role: CreateUserDtoRole;
}
