/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

export type SafeUserProfileDtoRole = typeof SafeUserProfileDtoRole[keyof typeof SafeUserProfileDtoRole];


export const SafeUserProfileDtoRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;
