/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

export interface TaskOwnerDto {
  /** Identificador único do proprietário */
  id: string;
  /** Nome do proprietário */
  name: string;
  /** E-mail do proprietário */
  email: string;
}
