/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

export type TasksControllerFindAllCategory = typeof TasksControllerFindAllCategory[keyof typeof TasksControllerFindAllCategory];


export const TasksControllerFindAllCategory = {
  TRABALHO: 'TRABALHO',
  ESTUDOS: 'ESTUDOS',
  PESSOAL: 'PESSOAL',
  OUTROS: 'OUTROS',
} as const;
